# Generated by Django 3.1.7 on 2021-03-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210310_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
